// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace uk.co.edgewords.webdrivercourse.Test_Cases
{
    [TestFixture]
    public class SelIDEDemoTestTest : Utilities.BaseTest
    {
        
        [Test, Category("Smoke")]
        public void selIDEDemoTest()
        {
            // Test name: SelIDEDemoTest
            // Step # | name | target | value
            // 1 | open | /webdriver2/ | 
            driver.Navigate().GoToUrl("https://www.edgewordstraining.co.uk/webdriver2/");
            // 2 | setWindowSize | 945x868 | 
            driver.Manage().Window.Size = new System.Drawing.Size(945, 868);
            //driver.Manage().Window.Maximize(); //XBrowser friendly way to maximize a window

            // 3 | click | css=.last span | 
            driver.FindElement(By.CssSelector(".last span")).Click();
            // 4 | click | linkText=Forms | 
            driver.FindElement(By.LinkText("Forms")).Click();
            // 5 | click | id=textInput | 
            driver.FindElement(By.Id("textInput")).Click();
            // 6 | type | id=textInput | Steve
            driver.FindElement(By.Id("textInput")).SendKeys("Steve");
            // 7 | click | id=textArea | 
            driver.FindElement(By.Id("textArea")).Click();
            // 8 | type | id=textArea | was\nhere\n
            driver.FindElement(By.Id("textArea")).SendKeys("was\nhere\n");
            // 9 | click | id=checkbox | 
            driver.FindElement(By.Id("checkbox")).Click();
            // 10 | click | id=select | 
            driver.FindElement(By.Id("select")).Click();
            // 11 | select | id=select | label=Selection Two
            {
                var dropdown = driver.FindElement(By.Id("select"));
                dropdown.FindElement(By.XPath("//option[. = 'Selection Two']")).Click();
            }
            // 12 | click | id=two | 
            driver.FindElement(By.Id("two")).Click();
            // 13 | click | id=password | 
            driver.FindElement(By.Id("password")).Click();
            // 14 | type | id=password | sdfasdfasdf
            driver.FindElement(By.Id("password")).SendKeys("sdfasdfasdf");
            // 15 | click | linkText=Submit | 
            driver.FindElement(By.LinkText("Submit")).Click();
            // 16 | click | css=tr:nth-child(2) > td:nth-child(3) | 
            driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(3)")).Click();
            // 17 | assertText | id=textInputValue | Steve
            Assert.That(driver.FindElement(By.Id("textInputValue")).Text, Is.EqualTo("Steve"));
            // 18 | click | css=h1 | 
            driver.FindElement(By.CssSelector("h1")).Click();
            // 19 | verifyText | css=h1 | Formsxxxxxx
            try
            {
                Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Formsxxxxxx"));
            }
            catch (Exception)
            {

                //throw; //NUnit specific hack - although the exception was "caught" the test still "Fails" with execution continuing.
            }
            
            // 20 | click | linkText=Home | 
            driver.FindElement(By.LinkText("Home")).Click();
        }
    }
}